# Site settings
title: Moexin&#039;s Blog
email: i@lmeoo.com
description: > # this means to ignore newlines until "baseurl:"
  Copyright @ 2017 <a href="http://blog.lmeoo.com/">Moexin's Blog</a> | 
  <a target="_blank" href="http://www.miitbeian.gov.cn/">桂ICP备16001758号-1</a> | 
  Powered by <a href="//lmeoo.com" target="_blank">Moexin</a> | 
  <a target="_blank" href="//uptime.statuscake.com/?TestID=EYMY0A1xb7">Monitor</a>
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.lmeoo.com" # the base hostname & protocol for your site
twitter_username: Amoeorz
github_username:  Moexin

# Build settings
markdown: kramdown
